export const categories = [
  {
    slug: "landing-pages",
    name: "Landing pages",
    description: "Page systems for turning traffic into qualified demos, trials, or waitlist demand.",
    icon: "LP",
    sortOrder: 1,
  },
  {
    slug: "creatives",
    name: "Creatives",
    description: "Ad and asset templates for hooks, proof, framing, and attention capture.",
    icon: "AD",
    sortOrder: 2,
  },
  {
    slug: "aeo-seo",
    name: "AEO/SEO",
    description: "Search and answer-engine loops built around intent capture, proof, and structured responses.",
    icon: "SEO",
    sortOrder: 3,
  },
  {
    slug: "pricing",
    name: "Pricing",
    description: "Packaging, positioning, and pricing page experiments that change buying motion.",
    icon: "PR",
    sortOrder: 4,
  },
  {
    slug: "emails",
    name: "E-mails",
    description: "Lifecycle and product email systems that move activation, expansion, and retention.",
    icon: "EM",
    sortOrder: 5,
  },
  {
    slug: "cold-outreach",
    name: "Cold outreach",
    description: "Outbound loops for message-market fit, list context, and positive reply rate.",
    icon: "CO",
    sortOrder: 6,
  },
  {
    slug: "warm-outreach",
    name: "Warm outreach",
    description: "Follow-up systems for inbound, PQL, event, and stakeholder expansion workflows.",
    icon: "WO",
    sortOrder: 7,
  },
  {
    slug: "ap-ar",
    name: "AP/AR",
    description: "Accounts payable and receivable communication loops that tighten cash operations.",
    icon: "AR",
    sortOrder: 8,
  },
  {
    slug: "procurement",
    name: "Procurement",
    description: "Vendor intake, review, negotiation, and approval workflows for faster purchasing.",
    icon: "PO",
    sortOrder: 9,
  },
];
